# The Most Basic Neural Network I Could Think Of
This is a basic neural network with a 3 perceptron input layer, a 4 perceptron hidden layer, and a 2 perceptron output layer. w0 is the weights from l0 to l1, and w1 is the weights from l1 to l2.

In [2]:
import numpy as np

Define the sigmoid function for perceptrons and its derivative.

In [3]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
def sigmoid_deriv(x):
    return x*(1-x)

Create the matricies for the layers and weights.

In [4]:
x = np.array([[0, 1, 0]])
y = np.array([[0, 1]])

w0 = 2*np.random.random((3,4)) - 1
w1 = 2*np.random.random((4,2)) - 1

print("Dimensions of matrices:")
print("x:", x.shape, "y:", y.shape, "w0:", w0.shape, "w1", w1.shape)

Dimensions of matrices:
x: (1, 3) y: (1, 2) w0: (3, 4) w1 (4, 2)


Make the network learn.

In [5]:
num_epochs = 60000
learn_rate = 0.1

for i in range(num_epochs):
    
    #Feedforward.
    l0 = x
    l1 = sigmoid(np.dot(l0, w0))
    l2 = sigmoid(np.dot(l1, w1))
    
    #Calculate errors and then backpropagate.
    E2 = y - l2
    d2 = E2 * sigmoid_deriv(l2)
    E1 = np.dot(d2, w1.T)
    d1 = E1 * sigmoid_deriv(l1)
    
    #I also have to do change in weights???
    
    #Update weight matricies.
    w1 += learn_rate * (np.dot(l1.T, d2))
    w0 += learn_rate * (np.dot(l0.T, d1))
    
    #See if the errors are getting smaller.
    if (i % 10000) == 0:
        print(w1)
        print(w0)
        print ("Error:" + str(np.mean(np.abs(E2))))
    

[[ 0.45891628  0.41599722]
 [-0.79312504 -0.49808311]
 [-0.80251959  0.38105612]
 [-0.69274921 -0.52446896]]
[[-0.41959446 -0.90284474  0.83580954 -0.77566249]
 [ 0.9733044   0.96671698  0.85715104  0.27792956]
 [ 0.0577301  -0.89779229 -0.18854363  0.43090738]]
Error:0.380842131415
[[-0.52800562  1.9023295 ]
 [-1.76613131  0.96791177]
 [-1.79451266  1.86489266]
 [-1.46524252  0.63450587]]
[[-0.41959446 -0.90284474  0.83580954 -0.77566249]
 [ 1.38400952  1.3450373   1.53322767  0.62536526]
 [ 0.0577301  -0.89779229 -0.18854363  0.43090738]]
Error:0.0141345679907
[[-0.63319422  2.01090607]
 [-1.87057924  1.07572376]
 [-1.90281027  1.9766783 ]
 [-1.5514363   0.72347541]]
[[-0.41959446 -0.90284474  0.83580954 -0.77566249]
 [ 1.43764166  1.40557665  1.60473178  0.69033292]
 [ 0.0577301  -0.89779229 -0.18854363  0.43090738]]
Error:0.00971717514063
[[-0.69295458  2.072397  ]
 [-1.92999457  1.13685964]
 [-1.96441284  2.04006478]
 [-1.60085652  0.77432671]]
[[-0.41959446 -0.90284474  0.8358095

This is a note about lambda expressions in Python.

In [ ]:
        # Note: in Python, you can define a function with a lambda expression,
        # as shown below.
        self.activation_function = lambda x : 1/(1+np.exp(-x))  # Replace 0 with your sigmoid calculation.
        
        ### If the lambda code above is not something you're familiar with,
        # You can uncomment out the following three lines and put your 
        # implementation there instead.
        #
        #def sigmoid(x):
        #    return 0  # Replace 0 with your sigmoid calculation here
        #self.activation_function = sigmoid